# =============================================================================
# Power Platform CI/CD Pipeline
# =============================================================================
# Triggers on merge to main branch
# Stages: Build → UAT (with approval) → Prod (with approval)
# =============================================================================

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/solutions/**
      - config/**

pr: none  # Don't trigger on PRs, only on merge

pool:
  vmImage: 'windows-latest'

variables:
  - group: PowerPlatform-Common
  - name: SolutionFolder
    value: 'src/solutions'
  - name: BuildArtifactName
    value: 'PowerPlatformSolutions'

stages:
  # ===========================================================================
  # BUILD STAGE
  # ===========================================================================
  - stage: Build
    displayName: 'Build Solutions'
    jobs:
      - job: BuildSolutions
        displayName: 'Export and Pack Solutions'
        steps:
          # Install Power Platform CLI
          - task: PowerPlatformToolInstaller@2
            displayName: 'Install Power Platform CLI'
            inputs:
              DefaultVersion: true

          # Authenticate to Dev environment
          - task: PowerPlatformSetConnectionVariables@2
            displayName: 'Set Connection Variables'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: 'PowerPlatform-Dev'

          # Export Connection References Solution (Unmanaged)
          - task: PowerPlatformExportSolution@2
            displayName: 'Export ConnectionRef (Unmanaged)'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: 'PowerPlatform-Dev'
              SolutionName: '$(ConnectionRefSolutionName)'
              SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/$(ConnectionRefSolutionName)_unmanaged.zip'
              Managed: false
              AsyncOperation: true
              MaxAsyncWaitTime: '60'

          # Export Connection References Solution (Managed)
          - task: PowerPlatformExportSolution@2
            displayName: 'Export ConnectionRef (Managed)'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: 'PowerPlatform-Dev'
              SolutionName: '$(ConnectionRefSolutionName)'
              SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/$(ConnectionRefSolutionName)_managed.zip'
              Managed: true
              AsyncOperation: true
              MaxAsyncWaitTime: '60'

          # Export Retainer Solution (Unmanaged)
          - task: PowerPlatformExportSolution@2
            displayName: 'Export Retainer (Unmanaged)'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: 'PowerPlatform-Dev'
              SolutionName: '$(SolutionName)'
              SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)_unmanaged.zip'
              Managed: false
              AsyncOperation: true
              MaxAsyncWaitTime: '60'

          # Export Retainer Solution (Managed)
          - task: PowerPlatformExportSolution@2
            displayName: 'Export Retainer (Managed)'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: 'PowerPlatform-Dev'
              SolutionName: '$(SolutionName)'
              SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)_managed.zip'
              Managed: true
              AsyncOperation: true
              MaxAsyncWaitTime: '60'

          # Unpack solutions for source control (optional - keeps repo in sync)
          - task: PowerPlatformUnpackSolution@2
            displayName: 'Unpack Retainer for Source Control'
            inputs:
              SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)_unmanaged.zip'
              SolutionTargetFolder: '$(Build.SourcesDirectory)/$(SolutionFolder)/$(SolutionName)'
              SolutionType: 'Both'
              ProcessCanvasApps: true

          # Copy configuration files
          - task: CopyFiles@2
            displayName: 'Copy Config Files'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/config'
              Contents: '**/*.json'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/config'

          # Copy scripts
          - task: CopyFiles@2
            displayName: 'Copy Scripts'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/scripts'
              Contents: '**/*'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/scripts'

          # Publish artifact
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(BuildArtifactName)'
              publishLocation: 'Container'

  # ===========================================================================
  # UAT DEPLOYMENT STAGE
  # ===========================================================================
  - stage: DeployToUAT
    displayName: 'Deploy to UAT'
    dependsOn: Build
    condition: succeeded()
    variables:
      - group: PowerPlatform-UAT
    jobs:
      - deployment: DeployUAT
        displayName: 'Deploy to UAT Environment'
        environment: 'UAT'  # This triggers approval gate
        strategy:
          runOnce:
            deploy:
              steps:
                # Install Power Platform CLI
                - task: PowerPlatformToolInstaller@2
                  displayName: 'Install Power Platform CLI'
                  inputs:
                    DefaultVersion: true

                # Import Connection References Solution
                - task: PowerPlatformImportSolution@2
                  displayName: 'Import ConnectionRef Solution'
                  inputs:
                    authenticationType: 'PowerPlatformSPN'
                    PowerPlatformSPN: '$(ServiceConnection)'
                    SolutionInputFile: '$(Pipeline.Workspace)/$(BuildArtifactName)/$(ConnectionRefSolutionName)_managed.zip'
                    AsyncOperation: true
                    MaxAsyncWaitTime: '60'
                    HoldingSolution: false
                    OverwriteUnmanagedCustomizations: true
                    PublishWorkflows: false

                # Import Retainer Solution
                - task: PowerPlatformImportSolution@2
                  displayName: 'Import Retainer Solution'
                  inputs:
                    authenticationType: 'PowerPlatformSPN'
                    PowerPlatformSPN: '$(ServiceConnection)'
                    SolutionInputFile: '$(Pipeline.Workspace)/$(BuildArtifactName)/$(SolutionName)_managed.zip'
                    AsyncOperation: true
                    MaxAsyncWaitTime: '60'
                    HoldingSolution: false
                    OverwriteUnmanagedCustomizations: true
                    PublishWorkflows: false
                    UseDeploymentSettingsFile: true
                    DeploymentSettingsFile: '$(Pipeline.Workspace)/$(BuildArtifactName)/config/deployment-settings-uat.json'

                # Set Environment Variables
                - task: PowerShell@2
                  displayName: 'Set Environment Variables'
                  inputs:
                    targetType: 'filePath'
                    filePath: '$(Pipeline.Workspace)/$(BuildArtifactName)/scripts/Set-EnvironmentVariables.ps1'
                    arguments: >
                      -EnvironmentUrl "$(EnvironmentUrl)"
                      -TenantId "$(TenantId)"
                      -ClientId "$(ServicePrincipalId)"
                      -ClientSecret "$(ServicePrincipalSecret)"
                      -ConfigFile "$(Pipeline.Workspace)/$(BuildArtifactName)/config/environment-variables-uat.json"

                # Activate Flows
                - task: PowerShell@2
                  displayName: 'Activate Flows'
                  inputs:
                    targetType: 'filePath'
                    filePath: '$(Pipeline.Workspace)/$(BuildArtifactName)/scripts/Activate-Flows.ps1'
                    arguments: >
                      -EnvironmentUrl "$(EnvironmentUrl)"
                      -TenantId "$(TenantId)"
                      -ClientId "$(ServicePrincipalId)"
                      -ClientSecret "$(ServicePrincipalSecret)"
                      -SolutionName "$(SolutionName)"

                # Publish Bot
                - task: PowerShell@2
                  displayName: 'Publish Copilot Bot'
                  inputs:
                    targetType: 'filePath'
                    filePath: '$(Pipeline.Workspace)/$(BuildArtifactName)/scripts/Publish-Bot.ps1'
                    arguments: >
                      -EnvironmentUrl "$(EnvironmentUrl)"
                      -TenantId "$(TenantId)"
                      -ClientId "$(ServicePrincipalId)"
                      -ClientSecret "$(ServicePrincipalSecret)"
                      -SolutionName "$(SolutionName)"

  # ===========================================================================
  # PROD DEPLOYMENT STAGE
  # ===========================================================================
  - stage: DeployToProd
    displayName: 'Deploy to Production'
    dependsOn: DeployToUAT
    condition: succeeded()
    variables:
      - group: PowerPlatform-Prod
    jobs:
      - deployment: DeployProd
        displayName: 'Deploy to Production Environment'
        environment: 'Prod'  # This triggers approval gate
        strategy:
          runOnce:
            deploy:
              steps:
                # Install Power Platform CLI
                - task: PowerPlatformToolInstaller@2
                  displayName: 'Install Power Platform CLI'
                  inputs:
                    DefaultVersion: true

                # Import Connection References Solution
                - task: PowerPlatformImportSolution@2
                  displayName: 'Import ConnectionRef Solution'
                  inputs:
                    authenticationType: 'PowerPlatformSPN'
                    PowerPlatformSPN: '$(ServiceConnection)'
                    SolutionInputFile: '$(Pipeline.Workspace)/$(BuildArtifactName)/$(ConnectionRefSolutionName)_managed.zip'
                    AsyncOperation: true
                    MaxAsyncWaitTime: '60'
                    HoldingSolution: false
                    OverwriteUnmanagedCustomizations: true
                    PublishWorkflows: false

                # Import Retainer Solution
                - task: PowerPlatformImportSolution@2
                  displayName: 'Import Retainer Solution'
                  inputs:
                    authenticationType: 'PowerPlatformSPN'
                    PowerPlatformSPN: '$(ServiceConnection)'
                    SolutionInputFile: '$(Pipeline.Workspace)/$(BuildArtifactName)/$(SolutionName)_managed.zip'
                    AsyncOperation: true
                    MaxAsyncWaitTime: '60'
                    HoldingSolution: false
                    OverwriteUnmanagedCustomizations: true
                    PublishWorkflows: false
                    UseDeploymentSettingsFile: true
                    DeploymentSettingsFile: '$(Pipeline.Workspace)/$(BuildArtifactName)/config/deployment-settings-prod.json'

                # Set Environment Variables
                - task: PowerShell@2
                  displayName: 'Set Environment Variables'
                  inputs:
                    targetType: 'filePath'
                    filePath: '$(Pipeline.Workspace)/$(BuildArtifactName)/scripts/Set-EnvironmentVariables.ps1'
                    arguments: >
                      -EnvironmentUrl "$(EnvironmentUrl)"
                      -TenantId "$(TenantId)"
                      -ClientId "$(ServicePrincipalId)"
                      -ClientSecret "$(ServicePrincipalSecret)"
                      -ConfigFile "$(Pipeline.Workspace)/$(BuildArtifactName)/config/environment-variables-prod.json"

                # Activate Flows
                - task: PowerShell@2
                  displayName: 'Activate Flows'
                  inputs:
                    targetType: 'filePath'
                    filePath: '$(Pipeline.Workspace)/$(BuildArtifactName)/scripts/Activate-Flows.ps1'
                    arguments: >
                      -EnvironmentUrl "$(EnvironmentUrl)"
                      -TenantId "$(TenantId)"
                      -ClientId "$(ServicePrincipalId)"
                      -ClientSecret "$(ServicePrincipalSecret)"
                      -SolutionName "$(SolutionName)"

                # Publish Bot
                - task: PowerShell@2
                  displayName: 'Publish Copilot Bot'
                  inputs:
                    targetType: 'filePath'
                    filePath: '$(Pipeline.Workspace)/$(BuildArtifactName)/scripts/Publish-Bot.ps1'
                    arguments: >
                      -EnvironmentUrl "$(EnvironmentUrl)"
                      -TenantId "$(TenantId)"
                      -ClientId "$(ServicePrincipalId)"
                      -ClientSecret "$(ServicePrincipalSecret)"
                      -SolutionName "$(SolutionName)"
